### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix, accuracy_score

### Loading Dataset

In [2]:
dataset = pd.read_csv('.//datasets//multi-class//segment.csv')
target_column = 'class'
dataset

region.centroid.col  region.centroid.row  region.pixel.count  \
0                     218                  178                   9   
1                     113                  130                   9   
2                     202                   41                   9   
3                      32                  173                   9   
4                      61                  197                   9   
...                   ...                  ...                 ...   
2305                   30                  102                   9   
2306                  143                   24                   9   
2307                   80                   72                   9   
2308                   98                  133                   9   
2309                   19                  147                   9   

      short.line.density.5  short.line.density.2  vedge.mean  vegde.sd  \
0                 0.111111                   0.0    0.833333  0.547722   
1                 0.000000                   0.0    0.277778  0.250924   
2                 0.000000                   0.0    0.944448  0.772202   
3                 0.000000                   0.0    1.722220  1.781590   
4                 0.000000                   0.0    1.444440  1.515350   
...                    ...                   ...         ...       ...   
2305              0.000000                   0.0    1.222220  0.118518   
2306              0.000000                   0.0    1.277780  0.907406   
2307              0.000000                   0.0    1.222220  1.003700   
2308              0.000000                   0.0    0.555555  0.172133   
2309              0.000000                   0.0    0.222222  0.074074   

      hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean  \
0       1.111110  0.544331       59.629600     52.44440      75.22220   
1       0.333333  0.365148        0.888889      0.00000       2.55556   
2       1.111110  1.025600      123.037000    111.88900     139.77800   
3       9.000000  6.749490       43.592600     39.55560      52.88890   
4       2.611110  1.925460       49.592600     44.22220      61.55560   
...          ...       ...             ...          ...           ...   
2305    1.333330  0.800000       20.259300     20.33330      25.00000   
2306    0.888888  1.140750      127.630000    117.66700     141.66700   
2307    1.444440  1.167460       59.000000     51.33330      74.44440   
2308    0.388889  0.327731        0.962963      0.00000       2.77778   
2309    0.500000  0.077778        4.148150      3.88889       6.66667   

      rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean  \
0         51.222200  -21.555600     46.77780     -25.22220    75.22220   
1          0.111111   -2.666670      5.00000      -2.33333     2.55556   
2        117.444000  -33.444400     50.22220     -16.77780   139.77800   
3         38.333300  -12.111100     27.88890     -15.77780    52.88890   
4         43.000000  -16.111100     35.88890     -19.77780    61.55560   
...             ...         ...          ...           ...         ...   
2305      15.444400    0.222222     14.22220     -14.44440    25.00000   
2306     123.556000  -29.888900     42.11110     -12.22220   141.66700   
2307      51.222200  -23.000000     46.33330     -23.33330    74.44440   
2308       0.111111   -2.888890      5.44444      -2.55556     2.77778   
2309       1.888890   -0.777778      7.55556      -6.77778     7.00000   

      saturation.mean  hue.mean      class  
0            0.318996  -2.04055       path  
1            1.000000  -2.12325    foliage  
2            0.199347  -2.29992        sky  
3            0.266914  -1.99886       path  
4            0.302925  -2.02227       path  
...               ...       ...        ...  
2305         0.381059  -1.55510  brickface  
2306         0.169397  -2.34925        sky  
2307         0.314606  -2.09022     cement  
2308         1.000000  -2.12325    foliage  
2309         0.

In [3]:
if "Unnamed: 0" in dataset.columns:
    dataset.drop("Unnamed: 0",axis=1,inplace=True)
dataset

region.centroid.col  region.centroid.row  region.pixel.count  \
0                     218                  178                   9   
1                     113                  130                   9   
2                     202                   41                   9   
3                      32                  173                   9   
4                      61                  197                   9   
...                   ...                  ...                 ...   
2305                   30                  102                   9   
2306                  143                   24                   9   
2307                   80                   72                   9   
2308                   98                  133                   9   
2309                   19                  147                   9   

      short.line.density.5  short.line.density.2  vedge.mean  vegde.sd  \
0                 0.111111                   0.0    0.833333  0.547722   
1                 0.000000                   0.0    0.277778  0.250924   
2                 0.000000                   0.0    0.944448  0.772202   
3                 0.000000                   0.0    1.722220  1.781590   
4                 0.000000                   0.0    1.444440  1.515350   
...                    ...                   ...         ...       ...   
2305              0.000000                   0.0    1.222220  0.118518   
2306              0.000000                   0.0    1.277780  0.907406   
2307              0.000000                   0.0    1.222220  1.003700   
2308              0.000000                   0.0    0.555555  0.172133   
2309              0.000000                   0.0    0.222222  0.074074   

      hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean  \
0       1.111110  0.544331       59.629600     52.44440      75.22220   
1       0.333333  0.365148        0.888889      0.00000       2.55556   
2       1.111110  1.025600      123.037000    111.88900     139.77800   
3       9.000000  6.749490       43.592600     39.55560      52.88890   
4       2.611110  1.925460       49.592600     44.22220      61.55560   
...          ...       ...             ...          ...           ...   
2305    1.333330  0.800000       20.259300     20.33330      25.00000   
2306    0.888888  1.140750      127.630000    117.66700     141.66700   
2307    1.444440  1.167460       59.000000     51.33330      74.44440   
2308    0.388889  0.327731        0.962963      0.00000       2.77778   
2309    0.500000  0.077778        4.148150      3.88889       6.66667   

      rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean  \
0         51.222200  -21.555600     46.77780     -25.22220    75.22220   
1          0.111111   -2.666670      5.00000      -2.33333     2.55556   
2        117.444000  -33.444400     50.22220     -16.77780   139.77800   
3         38.333300  -12.111100     27.88890     -15.77780    52.88890   
4         43.000000  -16.111100     35.88890     -19.77780    61.55560   
...             ...         ...          ...           ...         ...   
2305      15.444400    0.222222     14.22220     -14.44440    25.00000   
2306     123.556000  -29.888900     42.11110     -12.22220   141.66700   
2307      51.222200  -23.000000     46.33330     -23.33330    74.44440   
2308       0.111111   -2.888890      5.44444      -2.55556     2.77778   
2309       1.888890   -0.777778      7.55556      -6.77778     7.00000   

      saturation.mean  hue.mean      class  
0            0.318996  -2.04055       path  
1            1.000000  -2.12325    foliage  
2            0.199347  -2.29992        sky  
3            0.266914  -1.99886       path  
4            0.302925  -2.02227       path  
...               ...       ...        ...  
2305         0.381059  -1.55510  brickface  
2306         0.169397  -2.34925        sky  
2307         0.314606  -2.09022     cement  
2308         1.000000  -2.12325    foliage  
2309         0.

## Preprocessing

### Remove Date Columns

In [4]:
if "date" in dataset.columns:
    dataset.drop("date",inplace=True,axis=1)
    print("date Deleted")
if "Date" in dataset.columns:
    dataset.drop("Date",inplace=True,axis=1)
    print("Date Deleted")

### Remove Dollar signs

In [5]:
dollar = '$'
prices_list = []
if(len(dataset) > 100):
    for column in dataset.columns:
        X = dataset[column][:50].values
        for val in X:
            if( "$" in str(val)):
                prices_list.append(column)
                break;
            break;
            
prices_list

[]

In [6]:
new_2darray = []
if(prices_list):
    cost_values = dataset[prices_list].values
    for array in cost_values:
        new_array = []
        for val in array:
            new_val = (re.sub("[^0-9]", "", val))
            if new_val:
                new_val = float(new_val)
            else:
                new_val = np.NaN
            new_array.append(new_val)
        new_2darray.append(new_array)
new_2darray

[]

In [7]:
if(prices_list):
    prices_data = pd.DataFrame(new_2darray,columns= prices_list)

In [8]:
if(prices_list):
    dataset.drop(prices_list,inplace=True,axis=1)

In [9]:
if(prices_list):
    dataset[prices_list] = prices_data

### Define Index / ID Columns and Target Columns

In [10]:

id1 = "id"

### Categorize into numerical and categorical

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2310 entries, 0 to 2309
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   region.centroid.col   2310 non-null   int64  
 1   region.centroid.row   2310 non-null   int64  
 2   region.pixel.count    2310 non-null   int64  
 3   short.line.density.5  2310 non-null   float64
 4   short.line.density.2  2310 non-null   float64
 5   vedge.mean            2310 non-null   float64
 6   vegde.sd              2310 non-null   float64
 7   hedge.mean            2310 non-null   float64
 8   hedge.sd              2310 non-null   float64
 9   intensity.mean        2310 non-null   float64
 10  rawred.mean           2310 non-null   float64
 11  rawblue.mean          2310 non-null   float64
 12  rawgreen.mean         2310 non-null   float64
 13  exred.mean            2310 non-null   float64
 14  exblue.mean           2310 non-null   float64
 15  exgreen.mean         

In [12]:
datatypes = dataset.dtypes
datatypes

region.centroid.col       int64
region.centroid.row       int64
region.pixel.count        int64
short.line.density.5    float64
short.line.density.2    float64
vedge.mean              float64
vegde.sd                float64
hedge.mean              float64
hedge.sd                float64
intensity.mean          float64
rawred.mean             float64
rawblue.mean            float64
rawgreen.mean           float64
exred.mean              float64
exblue.mean             float64
exgreen.mean            float64
value.mean              float64
saturation.mean         float64
hue.mean                float64
class                    object
dtype: object

In [13]:
cat_cols = []
num_cols = []

columns = dataset.columns
if id1 in dataset.columns:
    dataset.drop(id1,inplace=True,axis=1)

for i in range(len(datatypes)):
    if datatypes.index[i] != target_column:
        if datatypes[i]=='object':
            unqval = dataset[datatypes.index[i]].nunique()
            if (unqval < 30):
                cat_cols.append(datatypes.index[i])
            else:
                del dataset[datatypes.index[i]]
                print('Deleted: ',datatypes.index[i])
        else:
            num_cols.append(datatypes.index[i])
num_cols

['region.centroid.col',
 'region.centroid.row',
 'region.pixel.count',
 'short.line.density.5',
 'short.line.density.2',
 'vedge.mean',
 'vegde.sd',
 'hedge.mean',
 'hedge.sd',
 'intensity.mean',
 'rawred.mean',
 'rawblue.mean',
 'rawgreen.mean',
 'exred.mean',
 'exblue.mean',
 'exgreen.mean',
 'value.mean',
 'saturation.mean',
 'hue.mean']

In [14]:
cat_cols

[]

In [15]:
cat_data = []
num_data = []
if(len(cat_cols)>0):
    cat_data = dataset[cat_cols]
if(len(num_cols)>0):
    num_data = dataset[num_cols]
y_data = dataset[target_column]

In [16]:
num_data,cat_data

(      region.centroid.col  region.centroid.row  region.pixel.count  \
 0                     218                  178                   9   
 1                     113                  130                   9   
 2                     202                   41                   9   
 3                      32                  173                   9   
 4                      61                  197                   9   
 ...                   ...                  ...                 ...   
 2305                   30                  102                   9   
 2306                  143                   24                   9   
 2307                   80                   72                   9   
 2308                   98                  133                   9   
 2309                   19                  147                   9   
 
       short.line.density.5  short.line.density.2  vedge.mean  vegde.sd  \
 0                 0.111111                   0.0    0.833333  0.547722

### Outlier Detection 

In [17]:
def outlier_detect(df):
    if (len(num_data)>0):        
        for i in df.describe().columns:
            Q1=df.describe().at['25%',i]
            Q3=df.describe().at['75%',i]
            IQR=Q3 - Q1
            LB=Q1 - 1.5 * IQR
            UB=Q3 + 1.5 * IQR
            x=np.array(df[i])
            p=[]
            for j in x:
                if j < LB or j>UB:
                   p.append(j)
            print('\n Outliers for Column : ', i, ' Outliers count ', len(p))
            print(p)
    else:
        print("Num_data is empty")

        
outlier_detect(num_data)


 Outliers for Column :  region.centroid.col  Outliers count  0
[]

 Outliers for Column :  region.centroid.row  Outliers count  0
[]

 Outliers for Column :  region.pixel.count  Outliers count  0
[]

 Outliers for Column :  short.line.density.5  Outliers count  278
[0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.222222, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.222222, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.222222, 0.111111, 0.333333, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.222222, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.111111, 0.


 Outliers for Column :  rawred.mean  Outliers count  174
[111.889, 135.111, 122.111, 130.667, 119.667, 113.778, 133.889, 116.556, 137.111, 116.0, 128.222, 115.778, 114.0, 117.0, 134.333, 129.444, 117.444, 115.667, 128.556, 114.667, 126.444, 111.333, 114.222, 132.556, 116.333, 115.444, 112.333, 130.444, 115.889, 112.556, 115.556, 130.333, 115.0, 112.333, 112.778, 119.222, 115.556, 116.333, 131.222, 116.222, 114.0, 116.0, 131.0, 115.0, 117.0, 129.0, 110.222, 115.556, 113.889, 110.222, 113.333, 117.667, 113.111, 115.556, 115.889, 110.778, 120.778, 131.556, 127.556, 110.556, 113.222, 111.0, 117.111, 118.333, 114.111, 130.778, 114.333, 127.556, 115.889, 136.889, 116.333, 131.444, 118.778, 110.667, 113.444, 114.444, 117.556, 120.778, 131.444, 129.889, 115.333, 114.0, 110.111, 113.667, 116.778, 113.444, 128.556, 115.333, 113.222, 111.444, 131.444, 117.778, 117.778, 116.556, 110.444, 112.333, 108.111, 112.222, 126.444, 109.222, 115.444, 132.556, 119.222, 109.889, 108.444, 123.222, 112.667, 10

### Treat Missing Values

In [18]:
if len(num_data):
    from sklearn.impute import SimpleImputer
    imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
    imputer.fit(num_data.iloc[:,:].values)
    num_data = pd.DataFrame(imputer.transform(num_data.iloc[:,:].values))
    num_data.columns = num_cols
num_data

region.centroid.col  region.centroid.row  region.pixel.count  \
0                   218.0                178.0                 9.0   
1                   113.0                130.0                 9.0   
2                   202.0                 41.0                 9.0   
3                    32.0                173.0                 9.0   
4                    61.0                197.0                 9.0   
...                   ...                  ...                 ...   
2305                 30.0                102.0                 9.0   
2306                143.0                 24.0                 9.0   
2307                 80.0                 72.0                 9.0   
2308                 98.0                133.0                 9.0   
2309                 19.0                147.0                 9.0   

      short.line.density.5  short.line.density.2  vedge.mean  vegde.sd  \
0                 0.111111                   0.0    0.833333  0.547722   
1                 0.000000                   0.0    0.277778  0.250924   
2                 0.000000                   0.0    0.944448  0.772202   
3                 0.000000                   0.0    1.722220  1.781590   
4                 0.000000                   0.0    1.444440  1.515350   
...                    ...                   ...         ...       ...   
2305              0.000000                   0.0    1.222220  0.118518   
2306              0.000000                   0.0    1.277780  0.907406   
2307              0.000000                   0.0    1.222220  1.003700   
2308              0.000000                   0.0    0.555555  0.172133   
2309              0.000000                   0.0    0.222222  0.074074   

      hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean  \
0       1.111110  0.544331       59.629600     52.44440      75.22220   
1       0.333333  0.365148        0.888889      0.00000       2.55556   
2       1.111110  1.025600      123.037000    111.88900     139.77800   
3       9.000000  6.749490       43.592600     39.55560      52.88890   
4       2.611110  1.925460       49.592600     44.22220      61.55560   
...          ...       ...             ...          ...           ...   
2305    1.333330  0.800000       20.259300     20.33330      25.00000   
2306    0.888888  1.140750      127.630000    117.66700     141.66700   
2307    1.444440  1.167460       59.000000     51.33330      74.44440   
2308    0.388889  0.327731        0.962963      0.00000       2.77778   
2309    0.500000  0.077778        4.148150      3.88889       6.66667   

      rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean  \
0         51.222200  -21.555600     46.77780     -25.22220    75.22220   
1          0.111111   -2.666670      5.00000      -2.33333     2.55556   
2        117.444000  -33.444400     50.22220     -16.77780   139.77800   
3         38.333300  -12.111100     27.88890     -15.77780    52.88890   
4         43.000000  -16.111100     35.88890     -19.77780    61.55560   
...             ...         ...          ...           ...         ...   
2305      15.444400    0.222222     14.22220     -14.44440    25.00000   
2306     123.556000  -29.888900     42.11110     -12.22220   141.66700   
2307      51.222200  -23.000000     46.33330     -23.33330    74.44440   
2308       0.111111   -2.888890      5.44444      -2.55556     2.77778   
2309       1.888890   -0.777778      7.55556      -6.77778     7.00000   

      saturation.mean  hue.mean  
0            0.318996  -2.04055  
1            1.000000  -2.12325  
2            0.199347  -2.29992  
3            0.266914  -1.99886  
4            0.302925  -2.02227  
...               ...       ...  
2305         0.381059  -1.55510  
2306         0.169397  -2.34925  
2307         0.314606  -2.09022  
2308         1.000000  -2.12325  
2309         0.713228  -1.47564  

[2310 rows x 19 columns]

In [19]:
if(len(cat_data)>0 and len(num_data)>0):
    print("1")
    df = pd.concat([num_data,cat_data,y_data],axis=1)
    df = df.dropna().reset_index(drop=True)
    df.isnull().sum()
elif(len(num_data) > 0):
    print("2")
    df = pd.concat([num_data,y_data],axis=1)
    df = df.dropna().reset_index(drop=True)
else:
    print("3")
    df = pd.concat([cat_data,y_data],axis=1)
    df = df.dropna().reset_index(drop=True)
(df)

2


region.centroid.col  region.centroid.row  region.pixel.count  \
0                   218.0                178.0                 9.0   
1                   113.0                130.0                 9.0   
2                   202.0                 41.0                 9.0   
3                    32.0                173.0                 9.0   
4                    61.0                197.0                 9.0   
...                   ...                  ...                 ...   
2305                 30.0                102.0                 9.0   
2306                143.0                 24.0                 9.0   
2307                 80.0                 72.0                 9.0   
2308                 98.0                133.0                 9.0   
2309                 19.0                147.0                 9.0   

      short.line.density.5  short.line.density.2  vedge.mean  vegde.sd  \
0                 0.111111                   0.0    0.833333  0.547722   
1                 0.000000                   0.0    0.277778  0.250924   
2                 0.000000                   0.0    0.944448  0.772202   
3                 0.000000                   0.0    1.722220  1.781590   
4                 0.000000                   0.0    1.444440  1.515350   
...                    ...                   ...         ...       ...   
2305              0.000000                   0.0    1.222220  0.118518   
2306              0.000000                   0.0    1.277780  0.907406   
2307              0.000000                   0.0    1.222220  1.003700   
2308              0.000000                   0.0    0.555555  0.172133   
2309              0.000000                   0.0    0.222222  0.074074   

      hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean  \
0       1.111110  0.544331       59.629600     52.44440      75.22220   
1       0.333333  0.365148        0.888889      0.00000       2.55556   
2       1.111110  1.025600      123.037000    111.88900     139.77800   
3       9.000000  6.749490       43.592600     39.55560      52.88890   
4       2.611110  1.925460       49.592600     44.22220      61.55560   
...          ...       ...             ...          ...           ...   
2305    1.333330  0.800000       20.259300     20.33330      25.00000   
2306    0.888888  1.140750      127.630000    117.66700     141.66700   
2307    1.444440  1.167460       59.000000     51.33330      74.44440   
2308    0.388889  0.327731        0.962963      0.00000       2.77778   
2309    0.500000  0.077778        4.148150      3.88889       6.66667   

      rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean  \
0         51.222200  -21.555600     46.77780     -25.22220    75.22220   
1          0.111111   -2.666670      5.00000      -2.33333     2.55556   
2        117.444000  -33.444400     50.22220     -16.77780   139.77800   
3         38.333300  -12.111100     27.88890     -15.77780    52.88890   
4         43.000000  -16.111100     35.88890     -19.77780    61.55560   
...             ...         ...          ...           ...         ...   
2305      15.444400    0.222222     14.22220     -14.44440    25.00000   
2306     123.556000  -29.888900     42.11110     -12.22220   141.66700   
2307      51.222200  -23.000000     46.33330     -23.33330    74.44440   
2308       0.111111   -2.888890      5.44444      -2.55556     2.77778   
2309       1.888890   -0.777778      7.55556      -6.77778     7.00000   

      saturation.mean  hue.mean      class  
0            0.318996  -2.04055       path  
1            1.000000  -2.12325    foliage  
2            0.199347  -2.29992        sky  
3            0.266914  -1.99886       path  
4            0.302925  -2.02227       path  
...               ...       ...        ...  
2305         0.381059  -1.55510  brickface  
2306         0.169397  -2.34925        sky  
2307         0.314606  -2.09022     cement  
2308         1.000000  -2.12325    foliage  
2309         0.

In [20]:
cat_data = df[cat_cols]
num_data = df[num_cols]
y_data = df[target_column]
df.drop(target_column,inplace=True,axis=1)
len(y_data)

2310

### One-hot encoding the categorical data

In [21]:
#if len(cat_cols):
from sklearn.preprocessing import OneHotEncoder

# Apply one-hot encoder to each column with categorical data
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
X_encoded = pd.DataFrame(OH_encoder.fit_transform(df[cat_cols]))

# One-hot encoding removed index; put it back
X_encoded.index = df.index

# Remove categorical columns (will replace with one-hot encoding)
num_X = df.drop(cat_cols, axis=1)

# Add one-hot encoded columns to numerical features
OH_X = pd.concat([num_X, X_encoded], axis=1)

In [22]:
OH_X

region.centroid.col  region.centroid.row  region.pixel.count  \
0                   218.0                178.0                 9.0   
1                   113.0                130.0                 9.0   
2                   202.0                 41.0                 9.0   
3                    32.0                173.0                 9.0   
4                    61.0                197.0                 9.0   
...                   ...                  ...                 ...   
2305                 30.0                102.0                 9.0   
2306                143.0                 24.0                 9.0   
2307                 80.0                 72.0                 9.0   
2308                 98.0                133.0                 9.0   
2309                 19.0                147.0                 9.0   

      short.line.density.5  short.line.density.2  vedge.mean  vegde.sd  \
0                 0.111111                   0.0    0.833333  0.547722   
1                 0.000000                   0.0    0.277778  0.250924   
2                 0.000000                   0.0    0.944448  0.772202   
3                 0.000000                   0.0    1.722220  1.781590   
4                 0.000000                   0.0    1.444440  1.515350   
...                    ...                   ...         ...       ...   
2305              0.000000                   0.0    1.222220  0.118518   
2306              0.000000                   0.0    1.277780  0.907406   
2307              0.000000                   0.0    1.222220  1.003700   
2308              0.000000                   0.0    0.555555  0.172133   
2309              0.000000                   0.0    0.222222  0.074074   

      hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean  \
0       1.111110  0.544331       59.629600     52.44440      75.22220   
1       0.333333  0.365148        0.888889      0.00000       2.55556   
2       1.111110  1.025600      123.037000    111.88900     139.77800   
3       9.000000  6.749490       43.592600     39.55560      52.88890   
4       2.611110  1.925460       49.592600     44.22220      61.55560   
...          ...       ...             ...          ...           ...   
2305    1.333330  0.800000       20.259300     20.33330      25.00000   
2306    0.888888  1.140750      127.630000    117.66700     141.66700   
2307    1.444440  1.167460       59.000000     51.33330      74.44440   
2308    0.388889  0.327731        0.962963      0.00000       2.77778   
2309    0.500000  0.077778        4.148150      3.88889       6.66667   

      rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean  \
0         51.222200  -21.555600     46.77780     -25.22220    75.22220   
1          0.111111   -2.666670      5.00000      -2.33333     2.55556   
2        117.444000  -33.444400     50.22220     -16.77780   139.77800   
3         38.333300  -12.111100     27.88890     -15.77780    52.88890   
4         43.000000  -16.111100     35.88890     -19.77780    61.55560   
...             ...         ...          ...           ...         ...   
2305      15.444400    0.222222     14.22220     -14.44440    25.00000   
2306     123.556000  -29.888900     42.11110     -12.22220   141.66700   
2307      51.222200  -23.000000     46.33330     -23.33330    74.44440   
2308       0.111111   -2.888890      5.44444      -2.55556     2.77778   
2309       1.888890   -0.777778      7.55556      -6.77778     7.00000   

      saturation.mean  hue.mean  
0            0.318996  -2.04055  
1            1.000000  -2.12325  
2            0.199347  -2.29992  
3            0.266914  -1.99886  
4            0.302925  -2.02227  
...               ...       ...  
2305         0.381059  -1.55510  
2306         0.169397  -2.34925  
2307         0.314606  -2.09022  
2308         1.000000  -2.12325  
2309         0.713228  -1.47564  

[2310 rows x 19 columns]

### Sampling/ Unbalanced Check

In [23]:
count = y_data.value_counts()
print(count)
print(max(count))
print(min(count))
cond = min(count)/max(count)
print(cond)

sky          330
cement       330
foliage      330
path         330
grass        330
window       330
brickface    330
Name: class, dtype: int64
330
330
1.0


### Label encoding y_data

In [24]:
from sklearn.preprocessing import LabelEncoder
if(y_data.dtypes == "object"):
    print(y_data.dtypes)
    le = LabelEncoder()
    y_data = le.fit_transform(y_data)
    y_data

object


In [25]:
from imblearn.over_sampling import ADASYN
from collections import Counter
if(cond<0.3):
    counter = Counter(y_data)
    print('before :',counter)
    ADA = ADASYN(random_state=130,sampling_strategy='minority')
    OH_X,y_data = ADA.fit_resample(OH_X,y_data)
    counter = Counter(y_data)
    print("after :",counter)

### Scaling

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
sc_x = StandardScaler()

In [28]:
OH_X = sc_x.fit_transform(OH_X)

In [29]:
OH_X

array([[ 1.2761887 ,  0.94973634,  0.        , ...,  0.70107202,
        -0.47269334, -0.4386101 ],
       [-0.16333606,  0.11453842,  0.        , ..., -0.99229686,
         2.51076426, -0.49213757],
       [ 1.05683255, -1.43405774,  0.        , ...,  2.20543198,
        -0.99687194, -0.60648701],
       ...,
       [-0.61575812, -0.89465908,  0.        , ...,  0.68294676,
        -0.4919258 , -0.47075894],
       [-0.36898245,  0.16673829,  0.        , ..., -0.98711841,
         2.51076426, -0.49213757],
       [-1.45205346,  0.41033768,  0.        , ..., -0.88872696,
         1.25442494, -0.0729728 ]])

In [30]:
model_accuracies = {}

In [31]:
from sklearn.metrics import roc_auc_score,accuracy_score, classification_report
def write_report(model, remarks, model_name):
 preds = model.predict(X_test)
 report = classification_report(y_test,preds)
 balanced_accuracy = '-'
 #roc_score = roc_auc_score(y_test, preds, multi_class='ovr')
 accuracyscore = accuracy_score(y_test, preds)
 print(f'\n{model}\n {report}\n  accuracy score: {accuracyscore}\n Remarks: {remarks}')
 with open(".//reports//"+model_name+"_report.txt", "w") as myfile:
   myfile.write(f'\n{model}\n {report}\n accuracy score: {accuracyscore}\n Remarks: {remarks}')

### Splitting Dataset

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test = train_test_split(OH_X,y_data,test_size=0.2,random_state=0)

## MODEL TRAINING

### Logistic Regression

In [34]:
from sklearn.linear_model import LogisticRegression
LR_classifier = LogisticRegression(random_state = 0)
LR_classifier.fit(X_train, y_train)

y_pred_lr = LR_classifier.predict(X_test)

/Users/samitkapadia/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [35]:
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)
lr_accuracy = accuracy_score(y_test, y_pred_lr)
model_accuracies["LogisticRegression"] = lr_accuracy
print(lr_accuracy)

[[65  0  0  0  0  0  2]
 [ 0 50  0  0  0  0  4]
 [ 0  2 56  0  0  0  8]
 [ 0  0  0 71  0  0  0]
 [ 0  0  0  0 70  0  0]
 [ 0  0  0  0  0 74  0]
 [ 0  7  8  0  0  0 45]]
0.9329004329004329


In [36]:
#write_report(LR_classifier,"good Model","Logistic Regression")

### Decision Tree Classifier

In [37]:
from sklearn.tree import DecisionTreeClassifier
DT_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
DT_classifier.fit(X_train, y_train)

y_pred_dr = DT_classifier.predict(X_test)

In [38]:
cm = confusion_matrix(y_test, y_pred_dr)
print(cm)
dt_accuracy = accuracy_score(y_test, y_pred_dr)
model_accuracies["DecisionTreeClassifer"] = dt_accuracy
print(dt_accuracy)

[[66  1  0  0  0  0  0]
 [ 0 50  1  0  0  0  3]
 [ 1  1 61  0  0  0  3]
 [ 0  0  0 71  0  0  0]
 [ 0  0  0  0 70  0  0]
 [ 0  0  0  0  0 74  0]
 [ 0  1  3  0  0  0 56]]
0.9696969696969697


In [39]:
write_report(DT_classifier,"good Model","Decision Tree Classifer")


DecisionTreeClassifier(criterion='entropy', random_state=0)
               precision    recall  f1-score   support

           0       0.99      0.99      0.99        67
           1       0.94      0.93      0.93        54
           2       0.94      0.92      0.93        66
           3       1.00      1.00      1.00        71
           4       1.00      1.00      1.00        70
           5       1.00      1.00      1.00        74
           6       0.90      0.93      0.92        60

    accuracy                           0.97       462
   macro avg       0.97      0.97      0.97       462
weighted avg       0.97      0.97      0.97       462

  accuracy score: 0.9696969696969697
 Remarks: good Model


### Random Forest classifier

In [40]:
from sklearn.ensemble import RandomForestClassifier
nodes = [10,15,20,25,50,100,200]
accuracy =[]
for node in nodes:    
    RandomForestclassifier = RandomForestClassifier(criterion = 'entropy', random_state=0, n_estimators=node)
    RandomForestclassifier.fit(X_train,y_train)
    preds = RandomForestclassifier.predict(X_test)
    accs = accuracy_score(y_test,preds)
    accuracy.append(accs)
    print(confusion_matrix(y_test,preds),'No of Estimators: ', node,accs)

# sns.lineplot(x=nodes,y=accuracy)
model_accuracies["RandomForestclassifier"] = accs

[[66  0  0  0  0  0  1]
 [ 0 52  1  0  0  0  1]
 [ 0  0 65  0  0  0  1]
 [ 0  0  0 71  0  0  0]
 [ 0  0  0  0 70  0  0]
 [ 0  0  0  0  0 74  0]
 [ 0  1  3  0  0  0 56]] No of Estimators:  10 0.9826839826839827
[[66  0  0  0  0  0  1]
 [ 0 52  1  0  0  0  1]
 [ 1  0 64  0  0  0  1]
 [ 0  0  0 71  0  0  0]
 [ 0  0  0  0 70  0  0]
 [ 0  0  0  0  0 74  0]
 [ 0  0  2  0  0  0 58]] No of Estimators:  15 0.9848484848484849
[[66  0  0  0  0  0  1]
 [ 0 51  1  0  0  0  2]
 [ 1  0 63  0  0  0  2]
 [ 0  0  0 71  0  0  0]
 [ 0  0  0  0 70  0  0]
 [ 0  0  0  0  0 74  0]
 [ 0  0  2  0  0  0 58]] No of Estimators:  20 0.9805194805194806
[[66  0  0  0  0  0  1]
 [ 0 51  1  0  0  0  2]
 [ 1  1 61  0  0  0  3]
 [ 0  0  0 71  0  0  0]
 [ 0  0  0  0 70  0  0]
 [ 0  0  0  0  0 74  0]
 [ 0  0  2  0  0  0 58]] No of Estimators:  25 0.9761904761904762
[[66  0  0  0  0  0  1]
 [ 0 51  1  0  0  0  2]
 [ 1  1 61  0  0  0  3]
 [ 0  0  0 71  0  0  0]
 [ 0  0  0  0 70  0  0]
 [ 0  0  0  0  0 74  0]
 [ 0  0  2  0  0

In [41]:
write_report(RandomForestclassifier,"good Model","RandomForestClassifier")


RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)
               precision    recall  f1-score   support

           0       0.99      0.99      0.99        67
           1       0.98      0.94      0.96        54
           2       0.95      0.94      0.95        66
           3       1.00      1.00      1.00        71
           4       1.00      1.00      1.00        70
           5       1.00      1.00      1.00        74
           6       0.92      0.97      0.94        60

    accuracy                           0.98       462
   macro avg       0.98      0.98      0.98       462
weighted avg       0.98      0.98      0.98       462

  accuracy score: 0.9783549783549783
 Remarks: good Model


### XgBoost Classifier

In [42]:
from xgboost import XGBClassifier   #XGBoostClassifier
XGboostclassifier = XGBClassifier(max_depth=6)
XGboostclassifier.fit(X_train, y_train)
y_pred = XGboostclassifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
xgboost_accuracy = accuracy_score(y_test, y_pred)
model_accuracies['XGboostclassifier'] = xgboost_accuracy

[01:31:43] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


/Users/samitkapadia/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[[66  0  0  0  0  0  1]
 [ 0 52  1  0  0  0  1]
 [ 1  0 63  0  0  0  2]
 [ 0  0  0 71  0  0  0]
 [ 0  0  0  0 70  0  0]
 [ 0  0  0  0  0 74  0]
 [ 0  1  2  0  0  0 57]]


In [43]:
write_report(XGboostclassifier,"good Model","XGboostclassifier")


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=4, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)
               precision    recall  f1-score   support

           0       0.99      0.99      0.99        67
           1       0.98      0.96      0.97        54
           2       0.95      0.95      0.95        66
           3       1.00      1.00      1.00        71
           4       1.00      1.00      1.00        70
           5       1.00      1.00      1.00   

### SVM Classifier


In [44]:
from sklearn.svm import SVC
SVCclassifier = SVC(kernel="rbf", random_state=0)
SVCclassifier.fit(X_train, y_train)
y_pred_svm = SVCclassifier.predict(X_test)

In [45]:
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)
svc_accuracy = accuracy_score(y_test, y_pred_svm)
model_accuracies["SVCclassifier"] = svc_accuracy

[[64  0  0  0  0  0  3]
 [ 0 49  1  0  0  0  4]
 [ 0  2 60  0  1  0  3]
 [ 0  0  0 71  0  0  0]
 [ 0  1  0  0 69  0  0]
 [ 0  1  0  0  0 73  0]
 [ 0  7  8  0  0  0 45]]


In [46]:
write_report(SVCclassifier,"good Model","SVCclassifier")


SVC(random_state=0)
               precision    recall  f1-score   support

           0       1.00      0.96      0.98        67
           1       0.82      0.91      0.86        54
           2       0.87      0.91      0.89        66
           3       1.00      1.00      1.00        71
           4       0.99      0.99      0.99        70
           5       1.00      0.99      0.99        74
           6       0.82      0.75      0.78        60

    accuracy                           0.93       462
   macro avg       0.93      0.93      0.93       462
weighted avg       0.93      0.93      0.93       462

  accuracy score: 0.9329004329004329
 Remarks: good Model


### Naive Bayes 

In [47]:
from sklearn.naive_bayes import GaussianNB
GaussianNBclassifier = GaussianNB()
GaussianNBclassifier.fit(X_train, y_train)
y_pred_nb = GaussianNBclassifier.predict(X_test)

In [48]:
cm = confusion_matrix(y_test, y_pred_nb)
print(cm)
nb_accuracy = accuracy_score(y_test, y_pred_nb)
model_accuracies["GaussianNBclassifie"] = nb_accuracy

[[63  3  0  0  0  0  1]
 [ 3 48  1  0  0  0  2]
 [ 3  3 13  0  0  0 47]
 [ 0  0  0 71  0  0  0]
 [ 0  2  0  0 68  0  0]
 [ 0  2  0  0  0 72  0]
 [13  5  4  0  0  0 38]]


In [49]:
write_report(GaussianNBclassifier,"good Model","GaussianNBclassifier")


GaussianNB()
               precision    recall  f1-score   support

           0       0.77      0.94      0.85        67
           1       0.76      0.89      0.82        54
           2       0.72      0.20      0.31        66
           3       1.00      1.00      1.00        71
           4       1.00      0.97      0.99        70
           5       1.00      0.97      0.99        74
           6       0.43      0.63      0.51        60

    accuracy                           0.81       462
   macro avg       0.81      0.80      0.78       462
weighted avg       0.83      0.81      0.79       462

  accuracy score: 0.8073593073593074
 Remarks: good Model


### Ada Boost

In [50]:
from sklearn.ensemble import AdaBoostClassifier
AdaboostClassifier = AdaBoostClassifier(n_estimators=100,learning_rate=1)
model = AdaboostClassifier.fit(X_train, y_train)
y_pred_ada = AdaboostClassifier.predict(X_test)

In [51]:
cm = confusion_matrix(y_test, y_pred_ada)
print(cm)
adaboost_accuracy = accuracy_score(y_test, y_pred_ada)
model_accuracies["AdaboostClassifier"] = adaboost_accuracy

[[ 0 67  0  0  0  0  0]
 [ 0 53  0  0  1  0  0]
 [ 0 65  0  0  0  1  0]
 [ 0  0  0 70  1  0  0]
 [ 0  2  0  0 68  0  0]
 [ 0  0  0  0  0 74  0]
 [ 0 60  0  0  0  0  0]]


In [52]:
write_report(AdaboostClassifier,"Good report","AdaboostClassifier")


AdaBoostClassifier(learning_rate=1, n_estimators=100)
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        67
           1       0.21      0.98      0.35        54
           2       0.00      0.00      0.00        66
           3       1.00      0.99      0.99        71
           4       0.97      0.97      0.97        70
           5       0.99      1.00      0.99        74
           6       0.00      0.00      0.00        60

    accuracy                           0.57       462
   macro avg       0.45      0.56      0.47       462
weighted avg       0.48      0.57      0.50       462

  accuracy score: 0.5735930735930735
 Remarks: Good report


/Users/samitkapadia/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/samitkapadia/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/samitkapadia/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

### Finding the best model

In [53]:
bestmodel = max(model_accuracies, key = model_accuracies.get)
print(bestmodel)
print(model_accuracies[bestmodel])

XGboostclassifier
0.9805194805194806


In [54]:
# rfc=RandomForestClassifier(random_state=42)

In [55]:
# param_grid = { 
#     'n_estimators': [200, 500],
#     'max_features': ['auto', 'sqrt', 'log2'],
#     'max_depth' : [4,5,6,7,8],
#     'criterion' :['gini', 'entropy']
# }

In [56]:
# from sklearn.model_selection import GridSearchCV
# CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
# CV_rfc.fit(X_train, y_train)
# CV_rfc.best_params_

In [57]:
# rfc=RandomForestClassifier(random_state=42,criterion= 'gini',max_depth=4,max_features= 'auto',n_estimators= 200)

In [58]:
# rfc.fit(X_train, y_train)
# preds = rfc.predict(X_test)
# accs = accuracy_score(y_test,preds)
# accuracy.append(accs)
# print(confusion_matrix(y_test,preds),'Accuracy: ',accs)